openapi: 3.1.3
info:
  version: 2.0.0
  title: Skeedy
servers:
  - url: https://localhost:4000/api
tags:
  - name: auth
    description: Точки входу сервера для реєстрації та авторизації користувачів
  - name: users
    description: API керування зареєстрованими користувачами
paths:
  /auth/google:
    $ref: api/auth/google.yaml
  /auth/registration:
    $ref: api/auth/registration.yaml
  /auth/login:
    $ref: api/auth/login.yaml
  /auth/refresh:
    $ref: api/auth/refresh.yaml
  /users/me:
    $ref: api/users/me.yaml
  /boards:
    $ref: api/boards/boards.yaml
  /boards/{id}:
    $ref: api/boards/board.yaml
components:
  securitySchemes:
    bearer:
      name: Authorization
      type: apiKey
      in: header
      description: Bearer JWT
security:
  - {}
  - bearer:
      - "write:all"
      - "read:all"
